version: '3.8'

services:
  front:
    image: node:16-alpine
    container_name: thapl.front
    command: [sh, -c, "npm i && npm run build && npm run start"]
    working_dir: '/thapl.front'
    tty: true
    volumes:
      - './:/thapl.front/'
    networks:
      - default
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
